name = "Wildlike Hexes"
author = "Gyro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d3f40784a6982da4e567a4c16a97d8f095180704c320ce80fc3551ad79aa0c"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
unsup = "1.2.7"
