name = "Wildlike Hexes"
author = "Gyro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0645ec13b11b69072f8fbdfeb109db08a05514138cc21370c8db77c368f2f321"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
unsup = "1.2.7"
