name = "Wildlike Hexes"
author = "Gyro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1368bcdfd7e575853c335ecfdde77c0adcf83736bdd9f8135f00027f5fba869"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
unsup = "1.2.7"
