[resourcepacks]
required = [
  "resourcepacks/AL's Skeletons Revamped+FA 1.5.3.zip",
  "resourcepacks/AL's Spiders Revamped+FA 1.5.zip",
  "resourcepacks/AL's Zombies Revamped+FA 1.4.1.zip",
  "resourcepacks/Assorted Allays x FA - V.11.0.zip",
  "resourcepacks/FA+Player-v1.1.zip",
  "resourcepacks/FA+All_Extensions-v1.8.1.zip",
  "resourcepacks/FreshAnimations_v1.10.4.zip",
  "resourcepacks/Brush+Juice-5.4.0.zip",
  "resourcepacks/elysiapresents_lootr.zip",
  "resourcepacks/Fancy Crops v1.3.zip",
  "resourcepacks/§3Fresh §bFlower Pots Compats§r.zip",
  "resourcepacks/§3Fresh §bFlower Pots.zip",
  "resourcepacks/Fresh Skeleton Physics.zip",
  "resourcepacks/Rocking Boats.zip",
  "resourcepacks/Wheat.zip",
  "resourcepacks/Tender Dragon v1.6.zip",
]
